/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./app/Livewire/**/*.php",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        teal: {
          50:  '#EBF4F6',
          100: '#d4e8ec',
          200: '#b0d5da',
          300: '#7AB2B2',
          400: '#3a9da8',
          500: '#088395',
          600: '#09637E',
          700: '#074e64',
          800: '#053a4b',
          900: '#032832',
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        smartk3: {
          "primary":          "#088395",
          "primary-content":  "#ffffff",
          "secondary":        "#09637E",
          "secondary-content":"#ffffff",
          "accent":           "#7AB2B2",
          "accent-content":   "#0a2e30",
          "neutral":          "#1e3a42",
          "neutral-content":  "#EBF4F6",
          "base-100":         "#ffffff",
          "base-200":         "#EBF4F6",
          "base-300":         "#d4e8ec",
          "base-content":     "#1a2e35",
          "info":             "#3b82f6",
          "info-content":     "#ffffff",
          "success":          "#22c55e",
          "success-content":  "#ffffff",
          "warning":          "#f59e0b",
          "warning-content":  "#1f2937",
          "error":            "#ef4444",
          "error-content":    "#ffffff",
        },
      },
      {
        smartk3dark: {
          "primary":          "#3aafbf",
          "primary-content":  "#0a1f24",
          "secondary":        "#5cc2d0",
          "secondary-content":"#0a1f24",
          "accent":           "#7AB2B2",
          "accent-content":   "#EBF4F6",
          "neutral":          "#1a2c32",
          "neutral-content":  "#c8dfe4",
          "base-100":         "#0f1c20",
          "base-200":         "#162428",
          "base-300":         "#1e3238",
          "base-content":     "#d4e8ec",
          "info":             "#60a5fa",
          "info-content":     "#0a1520",
          "success":          "#4ade80",
          "success-content":  "#0a200e",
          "warning":          "#fbbf24",
          "warning-content":  "#1f2937",
          "error":            "#f87171",
          "error-content":    "#200a0a",
        },
      },
    ],
    darkTheme: "smartk3dark",
  },
}
